train_config:
  train_dir: /truba/home/proj3/feras/Hirschsprung/dataset/hirschsprung/datasets/dataset13/Ege/model_mixed_after_model_results/Ege_Hospital_Internal_Test  # Directory containing training images
  test_dir: /truba/home/proj3/feras/Hirschsprung/dataset/hirschsprung/datasets/dataset13/Ege/model_mixed_after_model_results/Ege_Hospital_Internal_Test    # Directory containing test images
  save_dir: exp             # Directory to save the model and results
  batch_size: 16
  epochs: 50
  lr: 0.0001
  dropout: 0.5
  image_size: 512
  num_classes: 2
  linear_units: 2048
  weight_decay: 0.00001
  transformations:
    resize: [512, 512]
    to_tensor: true
    normalize_mean: [0.5, 0.5, 0.5]
    normalize_std: [0.5, 0.5, 0.5]
  transformations_jitter:
    resize: [512, 512]
    random_horizontal_flip: true
    random_vertical_flip: true
    random_rotation: 30
    color_jitter:
      brightness: 0.3
      contrast: 0.3
      saturation: 0.3
      hue: 0.1
    random_crop:
      size: [512, 512]
      padding: 10
    to_tensor: true
    normalize_mean: [0.5, 0.5, 0.5]
    normalize_std: [0.5, 0.5, 0.5]
